### ISSUE TITLE
Does it have to check for .xlsx extension?

### ISSUE THREAD

**Issue by ZombieHarvester** [TheFirstAvenger/elixir-xlsx_parser#13]
https://github.com/TheFirstAvenger/elixir-xlsx_parser/blob/a600dc1f4fa1c89705ff829eabe57ceb0ae8757c/lib/xlsx_parser/xlsx_util.ex#L45

Hi there!

Uploaded files don't have extension. You cannot send an uploaded file directly to xlsx_parser without copying or renaming it to .xlsx. 

Why does it have to be so strict on extension? Can we let it accept any filename?

Thanks

**Comment by TheFirstAvenger** [comment]
@ZombieHarvester v0.1.1 is available on hex which removes the extension check.

**Comment by ZombieHarvester** [comment]
@TheFirstAvenger hey thanks!
